os:
  - linux
  - osx

language: julia

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

git:
  depth: 99999

before_install:
  - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git"));'

jobs:
  include:
    - stage: deploy
      if: branch = master
      julia: 1.0
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.activate(); Pkg.add("Documenter"); Pkg.add("Literate"); Pkg.add("AxisArrays"); Pkg.add("Interpolations"); Pkg.add("Distances"); Pkg.add("JLD2"); Pkg.add("OrdinaryDiffEq"); Pkg.add("Clustering"); Pkg.add("Arpack"); Pkg.add("Plots"); Pkg.add("StaticArrays"); Pkg.add("Tensors"); Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git")); Pkg.clone(pwd()); Pkg.build("Plots"); Pkg.resolve(); Pkg.instantiate(); using Plots'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
