os:
  - linux
  - osx

language: julia

julia:
  - 1.0
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

git:
  depth: 99999

before_install:
  - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git"));'

jobs:
  include:
    - stage: deploy
      if: branch = master
      julia: 1.3
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.add("Plots"); Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git")); Pkg.clone(pwd()); Pkg.build("Plots"); Pkg.resolve(); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
