os:
    - linux

language: julia

julia:
    - 1.0
    - nightly

notifications: 
    email: false

git:
    depth: 99999


before_install:
      - julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git"));'

jobs:
  include:
    - stage: deploy
      julia: 1.0
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url = "https://github.com/KristofferC/JuAFEM.jl.git")); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

