name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(; url="https://github.com/KristofferC/JuAFEM.jl.git"))'
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main(; subdirs = ["", "docs"])
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DEPLOY_KEY_2_sec }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
